import CssBaseline from '@mui/material/CssBaseline'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Free Money Tools',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        {children}
      </body>
    </html>
  )
}
